'use client';

import {useEffect, useState, type ReactNode} from 'react';
import type {createAdminApi} from '@/lib/admin-api';
import {businessPlatforms, commercialFields, commercialTotals, documentKinds, documentMissing, formatMoney, opportunityFields, stageLabels, type BusinessStatus, type CommercialDocument, type Opportunity, type OpportunityFields} from '@/lib/business-contracts';
import styles from './admin-business.module.css';
import {AdminKnowledgePicker} from './admin-knowledge';
import {isFollowupDue, opportunitiesCsv} from '@/lib/business-export';

type Props = {api: ReturnType<typeof createAdminApi>; mode: 'business' | 'commercial'; onDirty: (dirty: boolean) => void; onBusy: (busy: boolean) => void};
const sourceLabels = {manual: '手动录入', import: '批量导入', website: '独立站询盘', chatwoot: '聚合收件箱', tikhub: 'TikHub 公开评论'};
const emptyLead: OpportunityFields = {name: '', company: '', contact: '', platform: '其他', kind: 'public', sourceUrl: '', requirements: '', market: '', stage: 'new', owner: '', nextAction: '', nextDate: '', notes: ''};
const csvTemplate = 'externalId,name,company,contact,platform,kind,sourceUrl,requirements\n示例编号-请替换,客户或账号名称,公司,客户提供的联系方式,TikTok,public,https://www.tiktok.com/,产品需求\n';
function downloadTemplate() {const url = URL.createObjectURL(new Blob(['\uFEFF' + csvTemplate], {type: 'text/csv;charset=utf-8'})); const a = document.createElement('a'); a.href = url; a.download = '商机导入模板.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);}
function Field({label, children}: {label: string; children: ReactNode}) {return <label className={styles.field}><span>{label}</span>{children}</label>;}

export function AdminBusiness({api, mode, onDirty, onBusy}: Props) {
  const [leads, setLeads] = useState<Opportunity[]>([]), [documents, setDocuments] = useState<CommercialDocument[]>([]);
  const [status, setStatus] = useState<BusinessStatus>(), [selected, setSelected] = useState<Opportunity>();
  const [leadDraft, setLeadDraft] = useState<OpportunityFields>(), [doc, setDoc] = useState<CommercialDocument>();
  const [dirty, setDirty] = useState(false), [busy, setBusy] = useState('正在读取'), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [query, setQuery] = useState(''), [stage, setStage] = useState(''), [page, setPage] = useState(1);
  const [leadId, setLeadId] = useState(''), [kind, setKind] = useState<CommercialDocument['kind']>('proposal');
  const [csv, setCsv] = useState(''), [inboxPage, setInboxPage] = useState(1), [videoId, setVideoId] = useState(''), [confirmed, setConfirmed] = useState(false);
  const [importDirty, setImportDirty] = useState(false);
  const [dueOnly, setDueOnly] = useState(false), [documentQuery, setDocumentQuery] = useState('');
  const today = new Date().toLocaleDateString('en-CA');
  useEffect(() => {onDirty(dirty || importDirty); return () => onDirty(false);}, [dirty, importDirty, onDirty]);
  useEffect(() => {onBusy(Boolean(busy)); return () => onBusy(false);}, [busy, onBusy]);
  useEffect(() => {
    const listener = (event: BeforeUnloadEvent) => {if (dirty || importDirty) event.preventDefault();};
    window.addEventListener('beforeunload', listener); return () => window.removeEventListener('beforeunload', listener);
  }, [dirty, importDirty]);
  useEffect(() => {
    let cancelled = false;
    api.businessSync('website').then(() => Promise.all([api.businessList(), api.commercialList(), api.businessStatus()])).then(([a, b, c]) => {
      if (cancelled) return; setLeads(a.items); setDocuments(b.items); setStatus(c); setLeadId(a.items[0]?.id ?? '');
    }).catch(cause => {if (!cancelled) setError(cause instanceof Error ? cause.message : '读取失败，请刷新重试');}).finally(() => {if (!cancelled) setBusy('');});
    return () => {cancelled = true;};
  }, [api]);
  async function refresh() {const [a, b, c] = await Promise.all([api.businessList(), api.commercialList(), api.businessStatus()]); setLeads(a.items); setDocuments(b.items); setStatus(c);}
  async function run(label: string, work: () => Promise<void>) {setBusy(label); setError(''); setNotice(''); try {await work();} catch (cause) {setError(cause instanceof Error ? cause.message : '操作失败，请重试');} finally {setBusy('');}}
  const mayLeave = () => !dirty || window.confirm('有未保存的内容，是否放弃修改？');
  function chooseLead(item?: Opportunity) {if (!mayLeave()) return; setSelected(item); setLeadDraft(item ?? {...emptyLead}); setDirty(false); setError('');}
  function chooseDoc(item: CommercialDocument) {if (!mayLeave()) return; setDoc(item); setDirty(false); setError('');}
  function editLead<K extends keyof OpportunityFields>(key: K, value: OpportunityFields[K]) {setLeadDraft(old => old ? {...old, [key]: value} : old); setDirty(true);}
  function editDoc<K extends keyof CommercialDocument>(key: K, value: CommercialDocument[K]) {setDoc(old => old ? {...old, [key]: value} : old); setDirty(true);}
  async function sync(source: 'website' | 'chatwoot' | 'tikhub' | 'import', input: unknown = {}) {const result = await api.businessSync(source, input); await refresh(); setNotice(`读取 ${result.received} 条，新增 ${result.added} 条，已有 ${result.skipped} 条保持原跟进记录。`);}
  async function saveLead() {
    if (!leadDraft) return; const result = opportunityFields.safeParse(leadDraft);
    if (!result.success) throw new Error(result.error.issues[0].message);
    const saved = selected ? await api.businessSave({...selected, ...result.data}) : await api.businessCreate(result.data);
    setSelected(saved); setLeadDraft(saved); setDirty(false); await refresh(); setLeadId(saved.id); setNotice('商机已保存，可在“方案与报价”中选择此客户。');
  }
  async function saveDoc() {
    if (!doc) return; const result = commercialFields.safeParse(doc);
    if (!result.success) throw new Error(result.error.issues.map(i => `${i.path.join('.')}: ${i.message}`).join('；'));
    const saved = await api.commercialSave(doc.id, {...result.data, version: doc.version}); setDoc(saved); setDirty(false); await refresh(); setNotice('已保存草稿；修改后需重新复核。');
  }
  const matching = leads.filter(item => (!dueOnly || isFollowupDue(item, today)) && (!stage || item.stage === stage) && `${item.name} ${item.company} ${item.contact} ${item.platform} ${item.requirements}`.toLowerCase().includes(query.toLowerCase()));
  const pages = Math.max(1, Math.ceil(matching.length / 20)), shown = matching.slice((Math.min(page, pages) - 1) * 20, Math.min(page, pages) * 20);
  const locked = Boolean(busy);
  const validDoc = doc ? commercialFields.safeParse(doc) : undefined;
  const totals = validDoc?.success ? commercialTotals(validDoc.data) : undefined;
  const missing = validDoc?.success ? documentMissing(validDoc.data) : ['有效的金额与数量'];
  return <div className={styles.workspace}>
    <header><p className={styles.eyebrow}>客户与业务</p><h1>{mode === 'business' ? '商务与机会' : '方案与报价'}</h1></header>
    {error && <div role="alert" className={styles.error}>{error}</div>}{notice && <div role="status" className={styles.notice}>{notice}</div>}{busy && <p role="status">{busy}…</p>}
    <div className={styles.toolbar}><button disabled={locked} onClick={() => void run('刷新列表', async () => {await sync('website');})}>刷新列表与网站询盘</button><span>{leads.length} 条商机 · {documents.length} 份文件</span></div>
    {mode === 'business' ? <>
      <details className={styles.panel}><summary>接入与导入 · 免费功能优先</summary>
        <div className={styles.connectionGrid}><section><h3>独立站询盘</h3><strong>已接通 · 无新增接口费用</strong></section>
          <section><h3>聚合社媒收件箱 · Chatwoot</h3><p>{status?.chatwoot.message ?? '正在检查配置'}</p><p>只同步已授权渠道的会话。具体平台取决于 Chatwoot 版本与渠道授权，不代表八个平台均已接通。</p><Field label="同步页码"><input type="number" min={1} max={10000} value={inboxPage} onChange={e => setInboxPage(Number(e.target.value))}/></Field><button disabled={locked || !status?.chatwoot.ready || !Number.isInteger(inboxPage) || inboxPage < 1} onClick={() => void run('同步聚合收件箱', () => sync('chatwoot', {page: inboxPage}))}>同步这一页会话</button></section>
          <section><h3>公开线索 · TikHub</h3><p>{status?.tikhub.message ?? '正在检查配置'}</p><p>读取指定 TikTok 视频首批最多 20 条公开评论；不会读取私信。日剩余请求：{status?.tikhub.remainingRequests ?? '—'}。</p><Field label="TikTok 视频 ID"><input value={videoId} onChange={e => setVideoId(e.target.value)} placeholder="视频链接中的数字 ID"/></Field><label className={styles.check}><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)}/>确认使用此账号额度调用一次，可能产生费用</label><button disabled={locked || !status?.tikhub.ready || !confirmed || !/^\d{10,25}$/.test(videoId) || !status.tikhub.remainingRequests} onClick={() => void run('读取公开评论', () => sync('tikhub', {videoId, confirmed}))}>读取并加入待筛选</button></section>
        </div><section className={styles.import}><h3>免费批量导入</h3><p>支持八个平台的 CSV 线索。externalId 用于去重；kind 填 public（公开线索）或 inbound（收到咨询）。每次最多 200 条，已有记录不会被覆盖。</p><button onClick={downloadTemplate}>下载 CSV 模板</button><Field label="选择 CSV 文件"><input type="file" accept=".csv,text/csv" disabled={locked} onChange={e => {const file = e.target.files?.[0]; if (!file) return; void run('读取 CSV', async () => {if(file.size > 500000) throw new Error('文件不得超过 500 KB'); setCsv(await file.text()); setImportDirty(true);}); e.target.value = '';}}/></Field><Field label="CSV 内容（可直接粘贴）"><textarea rows={4} maxLength={500000} value={csv} onChange={e => {setCsv(e.target.value); setImportDirty(Boolean(e.target.value));}}/></Field><button disabled={locked || !csv.trim()} onClick={() => void run('导入线索', async () => {await sync('import', {csv}); setCsv(''); setImportDirty(false);})}>导入线索</button></section>
      </details>
      <section className={styles.panel}><div className={styles.toolbar}><h2>线索与商机</h2><button disabled={locked || !matching.length} onClick={() => {const url = URL.createObjectURL(new Blob([opportunitiesCsv(matching)], {type: 'text/csv;charset=utf-8'})); const a = document.createElement('a'); a.href = url; a.download = '商机记录.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);}}>导出当前筛选</button><button aria-pressed={dueOnly} onClick={() => {setDueOnly(value => !value); setPage(1);}}>{dueOnly ? '显示全部商机' : `今日及逾期跟进 · ${leads.filter(item => isFollowupDue(item, today)).length}`}</button><button className={styles.primary} disabled={locked} onClick={() => chooseLead()}>新增线索</button></div><div className={styles.filters}><Field label="搜索客户、平台或需求"><input value={query} onChange={e => {setQuery(e.target.value); setPage(1);}}/></Field><Field label="阶段"><select value={stage} onChange={e => {setStage(e.target.value); setPage(1);}}><option value="">全部阶段</option>{Object.entries(stageLabels).map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select></Field></div>
        <div className={styles.tableWrap}><table><thead><tr><th>客户 / 账号</th><th>来源</th><th>阶段</th><th>负责人 / 下次跟进</th><th>操作</th></tr></thead><tbody>{shown.map(item => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.company || '公司待确认'}</small></td><td>{item.platform}<small>{item.kind === 'public' ? '公开线索 · 待确认需求' : '收到咨询'} · {sourceLabels[item.source]}</small></td><td>{stageLabels[item.stage]}</td><td>{item.owner || '未分配'}<small>{item.nextDate || '未安排'}{isFollowupDue(item, today) ? ' · 需要跟进' : ''}</small></td><td><button disabled={locked} onClick={() => chooseLead(item)}>查看与跟进</button></td></tr>)}</tbody></table></div>{!shown.length && !locked && <p className={styles.empty}>没有符合条件的线索。可新增线索、导入 CSV，或等待网站询盘。</p>}<div className={styles.toolbar}><span>第 {Math.min(page, pages)} / {pages} 页 · {matching.length} 条</span><button disabled={page <= 1} onClick={() => setPage(n => n - 1)}>上一页</button><button disabled={page >= pages} onClick={() => setPage(n => n + 1)}>下一页</button></div>
      </section>
      {leadDraft && <section className={styles.panel}><h2>{selected ? '跟进商机' : '新增线索'} {dirty && <small>· 未保存</small>}</h2><form onSubmit={e => {e.preventDefault(); void run('保存商机', saveLead);}}><fieldset disabled={locked} className={styles.form}><div className={styles.twoColumns}>
        {(['name', 'company', 'contact', 'market', 'owner'] as const).map(key => <Field key={key} label={{name: '客户 / 账号名称 *', company: '公司', contact: '客户提供的联系方式', market: '目标市场', owner: '负责人'}[key]}><input required={key === 'name'} maxLength={300} value={leadDraft[key]} onChange={e => editLead(key, e.target.value)}/></Field>)}
        <Field label="平台"><select value={leadDraft.platform} onChange={e => editLead('platform', e.target.value as Opportunity['platform'])}>{businessPlatforms.map(name => <option key={name}>{name}</option>)}</select></Field><Field label="线索类型"><select value={leadDraft.kind} onChange={e => editLead('kind', e.target.value as Opportunity['kind'])}><option value="public">公开线索（需求待确认）</option><option value="inbound">收到咨询</option></select></Field><Field label="阶段"><select value={leadDraft.stage} onChange={e => editLead('stage', e.target.value as Opportunity['stage'])}>{Object.entries(stageLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="下次跟进日期"><input type="date" value={leadDraft.nextDate} onChange={e => editLead('nextDate', e.target.value)}/></Field><Field label="来源链接"><input type="url" value={leadDraft.sourceUrl} onChange={e => editLead('sourceUrl', e.target.value)}/></Field></div>
        {(['requirements', 'nextAction', 'notes'] as const).map(key => <Field key={key} label={{requirements: '客户需求', nextAction: '下一步行动', notes: '跟进记录'}[key]}><textarea rows={key === 'requirements' ? 5 : 3} maxLength={key === 'nextAction' ? 2000 : 12000} value={leadDraft[key]} onChange={e => editLead(key, e.target.value)}/></Field>)}<div className={styles.toolbar}><button type="submit" className={styles.primary}>保存商机</button><button type="button" onClick={() => {if(mayLeave()) {setSelected(undefined); setLeadDraft(undefined); setDirty(false);}}}>关闭编辑</button>{!dirty && !locked && selected?.source === 'website' && <a href={`#inquiries/${selected.externalId}`}>查看原询盘与邮件</a>}</div></fieldset></form></section>}
    </> : <>
      <section className={styles.panel}><h2>从商机生成文件</h2><div className={styles.filters}><Field label="客户 / 商机"><select value={leadId} disabled={locked} onChange={e => setLeadId(e.target.value)}><option value="">请选择商机</option>{leads.map(item => <option value={item.id} key={item.id}>{item.name} · {item.company || item.platform}</option>)}</select></Field><Field label="文件类型"><select value={kind} onChange={e => setKind(e.target.value as CommercialDocument['kind'])}>{Object.entries(documentKinds).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><button className={styles.primary} disabled={locked || !leadId} onClick={() => {if(!mayLeave()) return; void run('生成草稿', async () => {setDoc(await api.commercialCreate(leadId, kind)); setDirty(false); await refresh(); setNotice('已生成草稿。价格、主体和条款请按实际情况填写。');});}}>生成草稿</button></div>{!leads.length && !locked && <p>请先在“商务与机会”中新增或导入一条线索。</p>}</section>
      <section className={styles.panel}><h2>文件记录</h2><Field label="搜索文件、客户或编号"><input value={documentQuery} onChange={e => setDocumentQuery(e.target.value)}/></Field><div className={styles.tableWrap}><table><thead><tr><th>文件 / 客户</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{documents.filter(item => `${item.title} ${item.buyer} ${item.number}`.toLowerCase().includes(documentQuery.toLowerCase())).map(item => <tr key={item.id}><td>{item.title}<small>{item.buyer} · {item.number}</small></td><td>{item.status === 'reviewed' ? '已复核 · 未发送' : '草稿'}</td><td>{new Date(item.updatedAt).toLocaleString('zh-CN')}</td><td><button disabled={locked} onClick={() => chooseDoc(item)}>打开文件</button></td></tr>)}</tbody></table></div>{!documents.length && <p className={styles.empty}>还没有文件。从上方选择客户，生成第一份草稿。</p>}</section>
      {doc && <section className={styles.panel}><div className={styles.toolbar}><h2>{documentKinds[doc.kind]}</h2><span>版本 {doc.version} · {dirty ? '未保存' : doc.status === 'reviewed' ? '已复核' : '草稿'}</span></div><p>{doc.number} · 保存了生成时的客户资料；后续商机修改不会覆盖本文件。</p><form onSubmit={e => {e.preventDefault(); void run('保存文件', saveDoc);}}><fieldset className={styles.form} disabled={locked}><div className={styles.twoColumns}>
        <Field label="文件标题"><input required maxLength={300} value={doc.title} onChange={e => editDoc('title', e.target.value)}/></Field><Field label="币种"><select value={doc.currency} onChange={e => editDoc('currency', e.target.value as CommercialDocument['currency'])}>{['USD', 'CNY', 'EUR', 'GBP'].map(c => <option key={c}>{c}</option>)}</select></Field><Field label="供应方主体与地址"><textarea rows={3} maxLength={12000} value={doc.seller} onChange={e => editDoc('seller', e.target.value)} placeholder="请填写实际签约公司全称及地址"/></Field><Field label="客户主体与地址"><textarea rows={3} maxLength={12000} value={doc.buyer} onChange={e => editDoc('buyer', e.target.value)}/></Field><Field label="联系人"><input maxLength={300} value={doc.contact} onChange={e => editDoc('contact', e.target.value)}/></Field><Field label="有效日期"><input type="date" value={doc.validUntil} onChange={e => editDoc('validUntil', e.target.value)}/></Field></div>
        <Field label="方案与工作范围"><textarea rows={8} maxLength={30000} value={doc.body} onChange={e => editDoc('body', e.target.value)}/></Field><AdminKnowledgePicker api={api} disabled={locked} onUse={value => {if (doc.body.length + value.length + 2 > 30000) {setError('方案正文过长，请精简后引用'); return;} editDoc('body', [doc.body, value].filter(Boolean).join('\n\n'));}}/><h3>产品与报价</h3>{doc.items.map((item, index) => <div className={styles.lineItem} key={index}><Field label={`产品 ${index + 1}`}><input required value={item.name} maxLength={300} onChange={e => editDoc('items', doc.items.map((row, i) => i === index ? {...row, name: e.target.value} : row))}/></Field><Field label="规格"><textarea rows={2} value={item.specification} maxLength={2000} onChange={e => editDoc('items', doc.items.map((row, i) => i === index ? {...row, specification: e.target.value} : row))}/></Field><Field label="数量"><input type="number" required min={1} max={100000} step={1} value={Number.isFinite(item.quantity) ? item.quantity : ''} onChange={e => editDoc('items', doc.items.map((row, i) => i === index ? {...row, quantity: e.target.valueAsNumber} : row))}/></Field><Field label="单位"><input value={item.unit} maxLength={300} onChange={e => editDoc('items', doc.items.map((row, i) => i === index ? {...row, unit: e.target.value} : row))}/></Field><Field label="单价（空白待定）"><input type="text" inputMode="decimal" value={item.unitPrice} onChange={e => editDoc('items', doc.items.map((row, i) => i === index ? {...row, unitPrice: e.target.value} : row))}/></Field><button type="button" disabled={doc.items.length === 1} onClick={() => editDoc('items', doc.items.filter((_, i) => i !== index))}>移除此项</button></div>)}<button type="button" disabled={doc.items.length >= 100} onClick={() => editDoc('items', [...doc.items, {name: '新产品', specification: '', quantity: 1, unit: '件', unitPrice: ''}])}>添加报价项</button>
        <div className={styles.twoColumns}><Field label="折扣金额"><input inputMode="decimal" value={doc.discount} onChange={e => editDoc('discount', e.target.value)}/></Field><Field label="运费（不另计税）"><input inputMode="decimal" value={doc.shipping} onChange={e => editDoc('shipping', e.target.value)}/></Field><Field label="税率 %（按折后商品金额计算）"><input type="number" min={0} max={100} step="0.01" value={Number.isFinite(doc.taxPercent) ? doc.taxPercent : ''} onChange={e => editDoc('taxPercent', e.target.valueAsNumber)}/></Field></div>
        <div className={styles.total}>{totals && !totals.incomplete && totals.discount > totals.subtotal ? '折扣不能超过商品小计，请修改后保存' : totals && !totals.incomplete ? <>商品小计 {formatMoney(totals.subtotal, doc.currency)} − 折扣 {formatMoney(totals.discount, doc.currency)} + 税额 {formatMoney(totals.tax, doc.currency)} + 运费 {formatMoney(totals.shipping, doc.currency)}<strong>合计 {formatMoney(totals.total, doc.currency)}</strong></> : '价格或数量待填写，尚无确定合计'}</div>
        {(['delivery', 'payment', 'terms'] as const).map(key => <Field key={key} label={{delivery: '交付与验收约定', payment: '付款约定', terms: '其他条款（按双方实际约定填写）'}[key]}><textarea rows={4} maxLength={key === 'terms' ? 30000 : 4000} value={doc[key]} onChange={e => editDoc(key, e.target.value)}/></Field>)}<p>{missing.length ? `待补全：${missing.join('、')}` : '必填商务信息已补齐，可保存后人工复核。'}</p>
        <div className={styles.toolbar}><button type="submit" className={styles.primary}>保存文件</button><button type="button" disabled={dirty || Boolean(missing.length) || doc.status === 'reviewed'} onClick={() => void run('标记复核', async () => {setDoc(await api.commercialReview(doc.id, doc.version)); await refresh(); setNotice('已标记为人工复核，未发送或签署。');})}>标记为已复核</button>{!dirty && <a href={api.resolveUrl(`/api/cms/business/documents/${doc.id}/export`)} target="_blank" rel="noreferrer">下载打印版 / 另存 PDF</a>}</div><p>下载 HTML 打印版，打开后可通过浏览器打印另存为 PDF。未保存的改动不会进入下载文件。</p>
        <div className={styles.toolbar}><span>沿用本文件的价格与条款：</span>{(['proposal', 'quote', 'contract'] as const).filter(k => k !== doc.kind).map(k => <button type="button" disabled={dirty} key={k} onClick={() => void run('生成关联文件', async () => {setDoc(await api.commercialCreate(doc.opportunityId, k, doc.id)); await refresh(); setNotice('关联文件已生成，保留原文件并独立保存。');})}>生成{documentKinds[k]}</button>)}</div>
      </fieldset></form><details className={styles.preview} open><summary>正文排版预览</summary><h2>{doc.title}</h2><p>{doc.body}</p><h3>交付与验收</h3><p>{doc.delivery || '待填写'}</p><h3>付款约定</h3><p>{doc.payment || '待填写'}</p><h3>其他条款</h3><p>{doc.terms || '待填写'}</p></details></section>}
    </>}
  </div>;
}
